version: '2'

services:
    web:
        build: .
        command: npm run start
        restart: always
        volumes:
            - ./dist:/server/dist
        ports:
            - '3000:3000'
            - '5858:5858'
    transpiler:
        build: .
        command: ['tsc', '-w']
        volumes:
            - ./dist:/server/src
            - /server/node_modules
